M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Thu 20 Jul 2023 04:44:24 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-20T16:44:24-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X110.31Y-61.93
X116.09Y-61.93
T0
M30
